### ISSUE TITLE
midagi on kaardi loogikaga perses

### ISSUE THREAD

**Issue by karl-k-m** [karl-k-m/scuffed-blackjack#1]
ei nagu mingi asi on kaardi loogikaga perses, ehk ta kas kuvab kaarte valesti või arvutab totalit valesti.

**Comment by GnuThe2nd** [comment]
Uuf jah sellega on väheke peetis. Kaardipaki defineerides oled pannud "value in range(1,14)", mis annab 13 kaardile jah väärtused, aga sel juhul nt kõige väiksema kaardi suurus on 2 kuigi selle value on 1. Props sealt kuskil lähebki kaartide loogika perse. Ma pullin ja hakkan fixima.
